# Generated by Django 4.0.5 on 2022-06-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
